/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import DTOS.ClienteDTO;
import DTOS.GuardarClienteDTO;
import Negocio.ClienteNegocio;
import Negocio.IClienteNegocio;
import Negocio.NegocioException;
import Persistencia.ClienteDAO;
import Persistencia.ConexionBD;
import Persistencia.IConexionBD;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author riosr
 */
public class frmDatosCliente extends javax.swing.JFrame {

    private IClienteNegocio clienteNegocio;
    private ClienteDTO cliente;

    public frmDatosCliente(IClienteNegocio clienteNegocio) {
        initComponents();
        this.clienteNegocio = clienteNegocio;
    }

    public frmDatosCliente(IClienteNegocio clienteNegocio, ClienteDTO cliente) {
        initComponents();
        this.clienteNegocio = clienteNegocio;
        this.cliente = cliente;
        obtenerDatos(cliente); 
    }

    public GuardarClienteDTO obtenerObjetoGuadarCliente() {
        String nombre = textDatosNombreCliente.getText();
        String apellidoPaterno = textDatosApellidoPaternoCliente.getText();
        String apellidoMaterno = textDatosApellidoMaternoCliente.getText();
         Integer idLaboratorio = 1;
        String fechaTexto = textDatosFechaNacimientoCliente.getText(); // Obtienes el texto del campo
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy"); // Asumiendo el formato "día-mes-año"
        LocalDate fechaNacimiento = LocalDate.parse(fechaTexto, formatter); // Convierte el texto a LocalDate

        return new GuardarClienteDTO(nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, idLaboratorio);
    }

    private void obtenerDatos(ClienteDTO cliente) {
        textDatosNombreCliente.setText(cliente.getNombres());
        textDatosApellidoPaternoCliente.setText(cliente.getApellidoPaterno());
        textDatosApellidoMaternoCliente.setText(cliente.getApellidoMaterno());

        // Formateo de la fecha de nacimiento a cadena
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String fechaNacimientoTexto = cliente.getFechaNacimiento().format(formatter); // Convertimos el LocalDate a String
        textDatosFechaNacimientoCliente.setText(fechaNacimientoTexto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textDatosNombreCliente = new javax.swing.JTextField();
        textDatosApellidoPaternoCliente = new javax.swing.JTextField();
        textDatosApellidoMaternoCliente = new javax.swing.JTextField();
        textDatosFechaNacimientoCliente = new javax.swing.JTextField();
        btnDatosClienteRegresar = new javax.swing.JButton();
        btnDatosClienteGuardar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Datos del Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");

        textDatosNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDatosNombreClienteActionPerformed(evt);
            }
        });

        textDatosApellidoPaternoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDatosApellidoPaternoClienteActionPerformed(evt);
            }
        });

        textDatosApellidoMaternoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDatosApellidoMaternoClienteActionPerformed(evt);
            }
        });

        textDatosFechaNacimientoCliente.setEditable(false);
        textDatosFechaNacimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDatosFechaNacimientoClienteActionPerformed(evt);
            }
        });

        btnDatosClienteRegresar.setText("Regresar ");
        btnDatosClienteRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosClienteRegresarActionPerformed(evt);
            }
        });

        btnDatosClienteGuardar.setText("Guardar");
        btnDatosClienteGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosClienteGuardarActionPerformed(evt);
            }
        });

        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnDatosClienteRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDatosClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDatosApellidoMaternoCliente)
                            .addComponent(textDatosFechaNacimientoCliente)
                            .addComponent(textDatosApellidoPaternoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDatosNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textDatosNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textDatosApellidoPaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(textDatosApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textDatosFechaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnDatosClienteRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDatosClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDatosApellidoMaternoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDatosApellidoMaternoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDatosApellidoMaternoClienteActionPerformed

    private void textDatosNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDatosNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDatosNombreClienteActionPerformed

    private void textDatosApellidoPaternoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDatosApellidoPaternoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDatosApellidoPaternoClienteActionPerformed

    private void textDatosFechaNacimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDatosFechaNacimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDatosFechaNacimientoClienteActionPerformed

    private void btnDatosClienteRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosClienteRegresarActionPerformed
       
       frmAdministrarClientes n= new frmAdministrarClientes(clienteNegocio);
       n.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_btnDatosClienteRegresarActionPerformed

    private void btnDatosClienteGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosClienteGuardarActionPerformed
          try {
        GuardarClienteDTO datosCliente = this.obtenerObjetoGuadarCliente();

        if (this.cliente == null) { 
            ClienteDTO nuevoCliente = this.clienteNegocio.guardar(datosCliente);
            JOptionPane.showMessageDialog(this, "Alumno guardado correctamente.", "Bien", JOptionPane.INFORMATION_MESSAGE);
        } else { // Si estamos editando un alumno existente
            ClienteDTO clienteEditado = new ClienteDTO(
                cliente.getId(),
                datosCliente.getNombres(),
                datosCliente.getApellidoPaterno(),
                datosCliente.getApellidoMaterno(),
                datosCliente.getFechaNacimiento()
            );
            this.clienteNegocio.editar(cliente.getId(), clienteEditado);
            JOptionPane.showMessageDialog(this, "Alumno actualizado correctamente.", "Bien", JOptionPane.INFORMATION_MESSAGE);
        }
     
       

    } catch (NegocioException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar el alumno: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnDatosClienteGuardarActionPerformed

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        if (evt.getOldValue() != null) {
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            textDatosFechaNacimientoCliente.setText(ff.format(jCalendar1.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jCalendar1PropertyChange

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatosClienteGuardar;
    private javax.swing.JButton btnDatosClienteRegresar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField textDatosApellidoMaternoCliente;
    private javax.swing.JTextField textDatosApellidoPaternoCliente;
    private javax.swing.JTextField textDatosFechaNacimientoCliente;
    private javax.swing.JTextField textDatosNombreCliente;
    // End of variables declaration//GEN-END:variables
}
